### ISSUE TITLE
jupyter and tensorflow

### ISSUE THREAD

**Issue by seanshpark** [seanshpark/journal#2]
running tensorfow with jupyter

**Comment by seanshpark** [comment]
install jupyter
```
pip install jupyter
```

**Comment by seanshpark** [comment]
Font:
- `.local/lib/python3.6/site-packages/notebook/static/style/style.min.css`

**Comment by seanshpark** [comment]
`static/components/codemirror/lib/codemirror.css`

```css
.CodeMirror {
  /* Set height, width, borders, and global font properties here */
  font-family: Consolas, monospace;
  height: 300px;
  color: black;
  direction: ltr;
}
```
